### ISSUE TITLE
What is your lispm font?

### ISSUE THREAD

**Issue by adlai** [dmb2/clx-tutorial#1]
https://github.com/dmb2/clx-tutorial/blob/7509db50a98ec038f958bc9e5502227e46c8a116/lterm.lisp#L59

**Comment by dmb2** [comment]
When I was super into making everything look like a lisp machine, I found a bitmap font for X somewhere... Its been a long time since I've messed with it.

It looked like this: 
https://www.are.na/block/1024969

Maybe this will work:
http://web.archive.org/web/20070305171237/http://www.eurogaran.com/downloads/lispmfont/

Alternatively, this might be a more modern packaging:
https://github.com/unjordy/LispM-Font

**Comment by adlai** [comment]
Thank you!
